# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QRadioButton
from PyQt5.QtWidgets import QTableWidgetItem


class MainWindow(object):
    currentCount = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget_content = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_content.setGeometry(QtCore.QRect(40, 80, 771, 291))
        self.stackedWidget_content.setObjectName("stackedWidget_content")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label_6 = QtWidgets.QLabel(self.page_1)
        self.label_6.setGeometry(QtCore.QRect(60, 71, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(self.page_1)
        self.comboBox.setGeometry(QtCore.QRect(180, 71, 440, 28))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.page_1)
        self.label_5.setGeometry(QtCore.QRect(90, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(self.page_1)
        self.textEdit.setGeometry(QtCore.QRect(180, 20, 440, 28))
        self.textEdit.setObjectName("textEdit")
        self.stackedWidget_content.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(90, 19, 391, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.tableWidget = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget.setGeometry(QtCore.QRect(88, 56, 585, 129))
        self.tableWidget.setObjectName("tableWidget")

        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(2)
        self.tableWidget.setHorizontalHeaderLabels(['云端数据目录或文件','迁移目标客户端目录','恢复状态'])
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.setColumnWidth(1,250)
        self.tableWidget.setColumnWidth(0,250)
        self.tableWidget.setColumnWidth(2,80)
        self.tableWidget.setRowHeight(0,50)
        self.tableWidget.setRowHeight(1,50)


        newItem = QTableWidgetItem('C:data/data')
        newItem.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        newItem2 = QTableWidgetItem('C:data/data')
        newItem2.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        newItem3 = QTableWidgetItem('C:data/data')
        newItem3.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        newItem4 = QTableWidgetItem('C:data/data')
        newItem4.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.radiobutton1 = QRadioButton()
        self.radiobutton2 = QRadioButton()

        self.radiobutton1.setText('选中')
        self.radiobutton2.setText('选中')
        self.tableWidget.setCellWidget(0, 2,self.radiobutton1)
        self.tableWidget.setCellWidget(1, 2,self.radiobutton2)
        self.tableWidget.setItem(0, 0, newItem)
        self.tableWidget.setItem(0, 1, newItem2)
        self.tableWidget.setItem(1, 0, newItem3)
        self.tableWidget.setItem(1, 1, newItem4)

        self.checkBox = QtWidgets.QCheckBox(self.page_2)
        self.checkBox.setGeometry(QtCore.QRect(88, 188, 545, 37))
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.stackedWidget_content.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setGeometry(QtCore.QRect(90, 24, 391, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(88, 56, 585, 129))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.checkBox_3 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_3.setGeometry(QtCore.QRect(88, 212, 545, 37))
        self.checkBox_3.setTristate(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_13 = QtWidgets.QLabel(self.page_3)
        self.label_13.setGeometry(QtCore.QRect(88, 192, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setGeometry(QtCore.QRect(336, 192, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.stackedWidget_content.addWidget(self.page_3)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.scrollArea = QtWidgets.QScrollArea(self.page_7)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 765, 289))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 600))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.comboBox_3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_3.setGeometry(QtCore.QRect(180, 68, 440, 28))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_3.setGeometry(QtCore.QRect(180, 18, 440, 28))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(60, 68, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setGeometry(QtCore.QRect(90, 17, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget_5.setGeometry(QtCore.QRect(78, 148, 585, 129))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(2)
        self.tableWidget_5.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setGeometry(QtCore.QRect(80, 116, 391, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.checkBox_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_5.setGeometry(QtCore.QRect(80, 288, 581, 37))
        self.checkBox_5.setTristate(False)
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setGeometry(QtCore.QRect(72, 504, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setGeometry(QtCore.QRect(74, 336, 391, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setGeometry(QtCore.QRect(320, 504, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.checkBox_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_4.setGeometry(QtCore.QRect(72, 524, 545, 37))
        self.checkBox_4.setTristate(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget_4.setGeometry(QtCore.QRect(72, 368, 585, 129))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setGeometry(QtCore.QRect(60, 16, 120, 80))
        self.widget_2.setObjectName("widget_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget_content.addWidget(self.page_7)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(192, 372, 417, 65))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_previous = QtWidgets.QPushButton(self.widget)
        self.button_previous.setMinimumSize(QtCore.QSize(120, 36))
        self.button_previous.setObjectName("button_previous")
        self.horizontalLayout_2.addWidget(self.button_previous)
        self.button_next = QtWidgets.QPushButton(self.widget)
        self.button_next.setMinimumSize(QtCore.QSize(120, 36))
        self.button_next.setObjectName("button_next")
        self.horizontalLayout_2.addWidget(self.button_next)
        self.button_close = QtWidgets.QPushButton(self.widget)
        self.button_close.setMinimumSize(QtCore.QSize(120, 36))
        self.button_close.setObjectName("button_close")
        self.horizontalLayout_2.addWidget(self.button_close)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(620, 32, 185, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("background-color: rgb(255, 56, 16);\n"
"border-color: rgb(19, 42, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(428, 32, 181, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background-color: rgb(255, 56, 16);\n"
"border-color: rgb(19, 42, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 32, 185, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(255, 56, 16);\n"
"border-color: rgb(19, 42, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(236, 32, 182, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color: rgb(255, 56, 16);\n"
"border-color: rgb(19, 42, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.widget.raise_()
        self.stackedWidget_content.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_content.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.button_previous, self.button_next)
        MainWindow.setTabOrder(self.button_next, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.button_close)

        self.button_previous.clicked.connect(self.slofPrevious)
        self.button_next.clicked.connect(self.slofNext)
        self.button_close.clicked.connect(self.slofClose)
        self.radiobutton1.clicked.connect(self.buttonIsChecked)

    def slofClose(self):
        MainWindow.exec_()

    def slofPrevious(self):
        if self.currentCount > 0:
            self.currentCount -= 1
            self.stackedWidget_content.setCurrentIndex(self.currentCount)
    def slofNext(self):
        if self.currentCount < 3:
            self.currentCount += 1
            self.stackedWidget_content.setCurrentIndex(self.currentCount)

    def buttonIsChecked(self):
        if self.radiobutton1.isChecked():
            self.radiobutton1.setText('未选中')
        else:
            self.radiobutton1.setText('选中')


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "迁移目标客户端："))
        self.comboBox.setItemText(0, _translate("MainWindow", "客户端110"))
        self.comboBox.setItemText(1, _translate("MainWindow", "客户端111"))
        self.comboBox.setItemText(2, _translate("MainWindow", "客户端112"))
        self.comboBox.setItemText(3, _translate("MainWindow", "客户端113"))
        self.comboBox.setItemText(4, _translate("MainWindow", "客户端115"))
        self.label_5.setText(_translate("MainWindow", "迁移原客户端："))
        self.label_10.setText(_translate("MainWindow", "确认云数据是否已经恢复到目标客户端："))
        self.checkBox.setText(_translate("MainWindow", "请确认：上述恢复列表已经包含了您所需要恢复的所有数据"))
        self.label_12.setText(_translate("MainWindow", "复制规则列表"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建列"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建列"))
        self.checkBox_3.setText(_translate("MainWindow", "请确认：上述规则将迁移到新客户端，原客户端上的所有原则将被删除。"))
        self.label_13.setText(_translate("MainWindow", "迁移原客户端操作系统："))
        self.label_14.setText(_translate("MainWindow", "迁移目标户端操作系统："))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "客户端110"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "客户端111"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "客户端112"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "客户端113"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "客户端115"))
        self.label_9.setText(_translate("MainWindow", "迁移目标客户端："))
        self.label_15.setText(_translate("MainWindow", "迁移原客户端："))
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_5.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建列"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建列"))
        self.label_19.setText(_translate("MainWindow", "确认云端数据是否已恢复到目标客户端"))
        self.checkBox_5.setText(_translate("MainWindow", "请确认：上述恢复列表已经包含了您所需要恢复的所有数据，其余未恢复的数据不需要恢复到新客户端"))
        self.label_16.setText(_translate("MainWindow", "迁移原客户端操作系统："))
        self.label_17.setText(_translate("MainWindow", "复制规则列表"))
        self.label_18.setText(_translate("MainWindow", "迁移目标户端操作系统："))
        self.checkBox_4.setText(_translate("MainWindow", "请确认：上述规则将迁移到新客户端，原客户端上的所有原则将被删除。"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建列"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建列"))
        self.button_previous.setText(_translate("MainWindow", "上一步"))
        self.button_next.setText(_translate("MainWindow", "下一步"))
        self.button_close.setText(_translate("MainWindow", "关闭"))
        self.label_4.setText(_translate("MainWindow", "确认"))
        self.label_3.setText(_translate("MainWindow", "复制规则迁移"))
        self.label.setText(_translate("MainWindow", "选择迁移目标客户端"))
        self.label_2.setText(_translate("MainWindow", "云端数据恢复确认"))




if __name__=="__main__":
    import sys
    app=QtWidgets.QApplication(sys.argv)
    mainwindow = QtWidgets.QMainWindow()
    entry=MainWindow()
    entry.setupUi(mainwindow)
    mainwindow.show()
    sys.exit(app.exec_())

