# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rules.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RulesForm(object):
    def setupUi(self, RulesForm):
        RulesForm.setObjectName("RulesForm")
        RulesForm.resize(729, 449)
        self.ruleTab = QtWidgets.QTabWidget(RulesForm)
        self.ruleTab.setEnabled(True)
        self.ruleTab.setGeometry(QtCore.QRect(40, 10, 681, 431))
        self.ruleTab.setObjectName("ruleTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(40, 20, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 54, 12))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(130, 20, 141, 21))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(130, 50, 141, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(40, 80, 111, 16))
        self.label_3.setObjectName("label_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 110, 271, 71))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(40, 230, 271, 71))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(40, 200, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(47, 340, 51, 16))
        self.label_5.setObjectName("label_5")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_3.setGeometry(QtCore.QRect(110, 340, 231, 20))
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(460, 370, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 370, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.ruleTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(60, 40, 71, 21))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_2.setGeometry(QtCore.QRect(60, 80, 71, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton.setGeometry(QtCore.QRect(140, 80, 41, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_2.setGeometry(QtCore.QRect(190, 80, 41, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_5.setGeometry(QtCore.QRect(240, 80, 41, 16))
        self.radioButton_5.setObjectName("radioButton_5")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(200, 40, 69, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(130, 40, 54, 21))
        self.label_11.setObjectName("label_11")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_7.setGeometry(QtCore.QRect(340, 40, 161, 21))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(300, 40, 31, 21))
        self.label_12.setObjectName("label_12")
        self.ruleTab.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(80, 70, 21, 21))
        self.label_13.setObjectName("label_13")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_5.setGeometry(QtCore.QRect(50, 20, 91, 21))
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(140, 70, 31, 21))
        self.label_14.setObjectName("label_14")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(100, 70, 31, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_3.setGeometry(QtCore.QRect(180, 70, 69, 21))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(270, 70, 131, 21))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(270, 110, 131, 21))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(140, 110, 31, 21))
        self.label_26.setObjectName("label_26")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_4.setGeometry(QtCore.QRect(180, 110, 69, 21))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 110, 31, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(80, 110, 21, 21))
        self.label_27.setObjectName("label_27")
        self.label_41 = QtWidgets.QLabel(self.tab_3)
        self.label_41.setGeometry(QtCore.QRect(270, 150, 131, 21))
        self.label_41.setObjectName("label_41")
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_8.setGeometry(QtCore.QRect(180, 150, 69, 21))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QtCore.QRect(100, 150, 31, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_42 = QtWidgets.QLabel(self.tab_3)
        self.label_42.setGeometry(QtCore.QRect(80, 150, 21, 21))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.tab_3)
        self.label_43.setGeometry(QtCore.QRect(140, 150, 31, 21))
        self.label_43.setObjectName("label_43")
        self.ruleTab.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_44 = QtWidgets.QLabel(self.tab_4)
        self.label_44.setGeometry(QtCore.QRect(40, 20, 61, 21))
        self.label_44.setObjectName("label_44")
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_12.setGeometry(QtCore.QRect(40, 70, 61, 16))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_13.setGeometry(QtCore.QRect(110, 70, 61, 16))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_14.setGeometry(QtCore.QRect(180, 70, 61, 16))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_15.setGeometry(QtCore.QRect(250, 70, 61, 16))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_16.setGeometry(QtCore.QRect(320, 70, 61, 16))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_17.setGeometry(QtCore.QRect(390, 70, 61, 16))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_27 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_27.setGeometry(QtCore.QRect(460, 70, 61, 16))
        self.checkBox_27.setObjectName("checkBox_27")
        self.label_62 = QtWidgets.QLabel(self.tab_4)
        self.label_62.setGeometry(QtCore.QRect(60, 110, 61, 21))
        self.label_62.setObjectName("label_62")
        self.label_81 = QtWidgets.QLabel(self.tab_4)
        self.label_81.setGeometry(QtCore.QRect(320, 110, 61, 21))
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.tab_4)
        self.label_82.setGeometry(QtCore.QRect(60, 150, 61, 21))
        self.label_82.setObjectName("label_82")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_13.setGeometry(QtCore.QRect(320, 150, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.treeWidget = QtWidgets.QTreeWidget(self.tab_4)
        self.treeWidget.setGeometry(QtCore.QRect(40, 190, 521, 192))
        self.treeWidget.setObjectName("treeWidget")
        self.timeEdit = QtWidgets.QTimeEdit(self.tab_4)
        self.timeEdit.setGeometry(QtCore.QRect(130, 110, 118, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.tab_4)
        self.timeEdit_2.setGeometry(QtCore.QRect(400, 110, 118, 22))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.spinBox = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox.setGeometry(QtCore.QRect(110, 150, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_5.setGeometry(QtCore.QRect(170, 150, 41, 21))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.ruleTab.addTab(self.tab_4, "")

        self.retranslateUi(RulesForm)
        self.ruleTab.setCurrentIndex(3)
        self.comboBox_3.setCurrentIndex(3)
        self.comboBox_4.setCurrentIndex(0)
        self.comboBox_8.setCurrentIndex(0)
        self.comboBox_5.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RulesForm)

    def retranslateUi(self, RulesForm):
        _translate = QtCore.QCoreApplication.translate
        RulesForm.setWindowTitle(_translate("RulesForm", "Form"))
        self.label.setText(_translate("RulesForm", "复制名称"))
        self.label_2.setText(_translate("RulesForm", "客户端"))
        self.label_3.setText(_translate("RulesForm", "*包含的目录和文件"))
        self.label_4.setText(_translate("RulesForm", "*不包含的目录和文件"))
        self.label_5.setText(_translate("RulesForm", "目标路径"))
        self.pushButton.setText(_translate("RulesForm", "提交"))
        self.pushButton_2.setText(_translate("RulesForm", "取消"))
        self.ruleTab.setTabText(self.ruleTab.indexOf(self.tab), _translate("RulesForm", "基本设置"))
        self.checkBox.setText(_translate("RulesForm", "加密"))
        self.checkBox_2.setText(_translate("RulesForm", "压缩"))
        self.radioButton.setText(_translate("RulesForm", "低"))
        self.radioButton_2.setText(_translate("RulesForm", "中"))
        self.radioButton_5.setText(_translate("RulesForm", "高"))
        self.comboBox.setItemText(0, _translate("RulesForm", "AES"))
        self.comboBox.setItemText(1, _translate("RulesForm", "EFS"))
        self.comboBox.setItemText(2, _translate("RulesForm", "MD5"))
        self.label_11.setText(_translate("RulesForm", "加密类型："))
        self.label_12.setText(_translate("RulesForm", "密钥："))
        self.ruleTab.setTabText(self.ruleTab.indexOf(self.tab_2), _translate("RulesForm", "压缩加密"))
        self.label_13.setText(_translate("RulesForm", "从"))
        self.checkBox_5.setText(_translate("RulesForm", "开启CDP"))
        self.label_14.setText(_translate("RulesForm", "天到"))
        self.lineEdit.setText(_translate("RulesForm", "0"))
        self.comboBox_3.setCurrentText(_translate("RulesForm", "4"))
        self.comboBox_3.setItemText(0, _translate("RulesForm", "1"))
        self.comboBox_3.setItemText(1, _translate("RulesForm", "2"))
        self.comboBox_3.setItemText(2, _translate("RulesForm", "3"))
        self.comboBox_3.setItemText(3, _translate("RulesForm", "4"))
        self.comboBox_3.setItemText(4, _translate("RulesForm", "5"))
        self.comboBox_3.setItemText(5, _translate("RulesForm", "6"))
        self.comboBox_3.setItemText(6, _translate("RulesForm", "7"))
        self.comboBox_3.setItemText(7, _translate("RulesForm", "8"))
        self.comboBox_3.setItemText(8, _translate("RulesForm", "9"))
        self.comboBox_3.setItemText(9, _translate("RulesForm", "10"))
        self.comboBox_3.setItemText(10, _translate("RulesForm", "11"))
        self.comboBox_3.setItemText(11, _translate("RulesForm", "12"))
        self.comboBox_3.setItemText(12, _translate("RulesForm", "13"))
        self.comboBox_3.setItemText(13, _translate("RulesForm", "14"))
        self.comboBox_3.setItemText(14, _translate("RulesForm", "15"))
        self.label_24.setText(_translate("RulesForm", "保存连续的CDP数据"))
        self.label_25.setText(_translate("RulesForm", "保存合并的CDP数据"))
        self.label_26.setText(_translate("RulesForm", "天到"))
        self.comboBox_4.setCurrentText(_translate("RulesForm", "30"))
        self.comboBox_4.setItemText(0, _translate("RulesForm", "30"))
        self.comboBox_4.setItemText(1, _translate("RulesForm", "40"))
        self.comboBox_4.setItemText(2, _translate("RulesForm", "50"))
        self.comboBox_4.setItemText(3, _translate("RulesForm", "60"))
        self.lineEdit_2.setText(_translate("RulesForm", "4"))
        self.label_27.setText(_translate("RulesForm", "从"))
        self.label_41.setText(_translate("RulesForm", "按30天保存的CDP数据"))
        self.comboBox_8.setCurrentText(_translate("RulesForm", "180"))
        self.comboBox_8.setItemText(0, _translate("RulesForm", "180"))
        self.comboBox_8.setItemText(1, _translate("RulesForm", "270"))
        self.comboBox_8.setItemText(2, _translate("RulesForm", "360"))
        self.lineEdit_5.setText(_translate("RulesForm", "30"))
        self.label_42.setText(_translate("RulesForm", "从"))
        self.label_43.setText(_translate("RulesForm", "天到"))
        self.ruleTab.setTabText(self.ruleTab.indexOf(self.tab_3), _translate("RulesForm", "CDP设置"))
        self.label_44.setText(_translate("RulesForm", "宽带控制"))
        self.checkBox_12.setText(_translate("RulesForm", "星期一"))
        self.checkBox_13.setText(_translate("RulesForm", "星期二"))
        self.checkBox_14.setText(_translate("RulesForm", "星期三"))
        self.checkBox_15.setText(_translate("RulesForm", "星期四"))
        self.checkBox_16.setText(_translate("RulesForm", "星期五"))
        self.checkBox_17.setText(_translate("RulesForm", "星期六"))
        self.checkBox_27.setText(_translate("RulesForm", "星期日"))
        self.label_62.setText(_translate("RulesForm", "开始时间："))
        self.label_81.setText(_translate("RulesForm", "结束时间："))
        self.label_82.setText(_translate("RulesForm", "带宽："))
        self.pushButton_13.setText(_translate("RulesForm", "添加"))
        self.treeWidget.headerItem().setText(0, _translate("RulesForm", "星期"))
        self.treeWidget.headerItem().setText(1, _translate("RulesForm", "时间"))
        self.treeWidget.headerItem().setText(2, _translate("RulesForm", "带宽"))
        self.treeWidget.headerItem().setText(3, _translate("RulesForm", "操作"))
        self.comboBox_5.setCurrentText(_translate("RulesForm", "Mb"))
        self.comboBox_5.setItemText(0, _translate("RulesForm", "Mb"))
        self.comboBox_5.setItemText(1, _translate("RulesForm", "Kb"))
        self.ruleTab.setTabText(self.ruleTab.indexOf(self.tab_4), _translate("RulesForm", "宽带控制"))

